session: ${app}

root: ${path}

before_start:
  []
  # - if [ -f docker-compose.yml ]; then docker-compose up -d; fi

stop:
  []
  # - if [ -f docker-compose.yml ]; then docker-compose down; fi

windows:
  - name: nvim
    commands:
      - vim
